# Generated by Django 3.2.4 on 2021-07-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employee_eemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eclass',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
